//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DuiDesigner.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_TOOLBAR_FORMEDIT            101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_HC                129
#define IDR_UIDESIGNER                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define IDR_PROJECT_NEW                 135
#define ID_OPEN                         136
#define ID_DIRECTORY_NEW                137
#define ID_CREATE_COPY                  138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_PROPERTIES_TOOLBAR_ALPHABETIC 151
#define ID_PROPERTIES_TOOLBAR_SORT      152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_RESOURCE_VIEW               157
#define IDS_PROPERTIES_WND              158
#define IDS_TOOLBOX_WND                 159
#define ID_VIEW_TOOLBOX                 160
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_PROJECT_EXPLORER            169
#define IDB_PROJECT_EXPLORER_24         170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_RESOURCE                190
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_RESOURCE                    307
#define IDB_RESOURCE_VIEW               310
#define IDR_POPUP_RESOURCE              311
#define IDB_RESOURCE_VIEW24             311
#define IDD_DIALOG_IMAGE                312
#define IDI_RES_VIEW                    313
#define IDI_RES_VIEW_HC                 314
#define IDD_PROPERTY_TABLAYOUTUI        315
#define IDI_TOOLBOX_WND_HC              316
#define IDB_BITMAP_MOVEHANDLE           317
#define ID_VIEW_FORMEDIT_TOOLBAR        318
#define IDR_FORMEDIT                    319
#define ID_FORMEDIT_TEST                320
#define ID_FORMEDIT_ALIGN_LEFT          321
#define IDR_UI                          321
#define ID_FORMEDIT_ALIGN_RIGHT         322
#define IDD_PROJECT_NEW                 322
#define ID_FORMEDIT_ALIGN_TOP           323
#define IDD_SKINFILE_NEW                323
#define ID_FORMEDIT_ALIGN_BOTTOM        324
#define IDI_TOOLBOX_ACTIVE              324
#define ID_FORMEDIT_ALIGN_CENTER_VERTICALLY 325
#define IDI_TOOLBOX_BUTTON              325
#define ID_FORMEDIT_ALIGN_CENTER_HORIZONTALLY 326
#define IDI_TOOLBOX_OPTION              326
#define ID_FORMEDIT_ALIGN_HORIZONTAL    327
#define IDI_TOOLBOX_COMBO               327
#define ID_FORMEDIT_ALIGN_VERTICAL      328
#define IDI_TOOLBOX_CONTAINER           328
#define ID_FORMEDIT_ALIGN_SAME_WIDTH    329
#define IDI_TOOLBOX_CONTROL             329
#define ID_FORMEDIT_ALIGN_SAME_HEIGHT   330
#define ID_FORMEDIT_ALIGN_SAME_SIZE     331
#define IDI_TOOLBOX_EDIT                331
#define ID_FORMEDIT_SHOW_GRID           332
#define IDI_TOOLBOX_HORIZONTAL_LAYOUT   332
#define ID_FORMEDIT_SHOW_AUXBORDER      333
#define IDI_TOOLBOX_LABEL               333
#define ID_PROJECT_NEW                  334
#define IDI_TOOLBOX_POINTER             334
#define ID_FILE_SAVE_ALL                335
#define IDI_TOOLBOX_PROGRESS            335
#define IDR_FILE_NEW                    336
#define IDI_TOOLBOX_SCROLLBAR           336
#define IDR_FILE_DELETE                 337
#define IDI_TOOLBOX_SLIDER              337
#define ID_FILE_RENAME                  338
#define IDI_TOOLBOX_TAB_LAYOUT          338
#define ID_TREE_EXPAND                  339
#define IDI_TOOLBOX_TEXT                339
#define ID_TREE_COLLAPSE                340
#define IDI_TOOLBOX_TILELAYOUT          340
#define IDI_TOOLBOX_TILE_LAYOUT         340
#define IDI_TOOLBOX_VERTICAL_LAYOUT     341
#define IDD_DIALOG__SAVE_AS_NAME        342
#define IDD_DIALOG_TEMPLATE_OPEN        343
#define IDR_POPUP_MDITABS               344
#define IDD_DIALOG_CUSTOM_FONTS         345
#define IDD_DIALOG_DEFAULT_ATTRIB_LIST  346
#define IDB_BITMAP_ABOUT_BANNER         346
#define IDB_ABOUT_BANNER                346
#define ID_UI_PROP_WND                  347
#define IDD_DIALOG_UI_ATTRIB_EDIT       348
#define IDR_MENU_UI                     349
#define IDD_DIALOG_CHECK_UPDATE         350
#define IDC_BUTTON_IMAGE_IMPORT         1000
#define IDC_BUTTON_IMAGE_CLEAR          1001
#define IDC_LIST_IMAGE_RESOURCE         1002
#define IDC_EDIT_IMAGE_DEST             1003
#define IDC_EDIT_IMAGE_CORNER           1004
#define IDC_EDIT_IMAGE_SOURCE           1005
#define IDC_BUTTON_IMAGE_MASK           1006
#define IDC_SLIDER_IMAGE_FADE           1007
#define IDC_EDIT_IMAGE_FADE             1008
#define IDC_STATIC_IMAGE_PRE            1010
#define IDC_STATIC_IMAGE_PREVIEW        1010
#define IDC_RADIO_IMAGE_HOLE_FALSE      1011
#define IDC_RADIO_IMAGE_HOLE_TRUE       1012
#define IDC_LIST_TABLAYOUTUI_TAB        1012
#define IDC_BUTTON_TABLAYOUTUI_ADD      1013
#define IDC_BUTTON_BRO                  1014
#define IDC_BUTTON_BROWSE               1014
#define IDC_EDIT_PROJECT_NAME           1015
#define IDC_EDIT_PROJECT_PATH           1016
#define IDC_EDIT_FILE_NAME              1017
#define IDC_LIST_STYLE                  1020
#define IDC_STATIC_PREVIEW              1021
#define IDC_EDIT_TEMPLATE_NAME          1022
#define IDC_LIST_TEMPLATES              1023
#define IDC_BUTTON_TEMPLATE_DELETE      1024
#define IDC_STATIC_TEMPLATE_PREVIEW     1025
#define IDC_LIST_CUSTOM_FONTS           1026
#define IDC_BUTTON_FONT_DELETE          1027
#define IDC_BUTTON_FONT_ADD             1028
#define IDC_BUTTON_FONT_MODIFY          1029
#define IDC_STATIC_UI_PROP_LOCATION     1032
#define IDC_BUTTON_ATTRIB_ADD           1033
#define IDC_BUTTON_ATTRIB_DELETE        1034
#define IDC_BUTTON_ATTRIB_MODIFY        1035
#define IDC_LIST_DEFAULT_ATTRIB         1037
#define IDC_BUTTON_SAVE_AS_STYLE        1038
#define IDC_BUTTON_VERSION_UPDATE_LINK  1038
#define IDC_BUTTON_MY_BLOG_LINK         1038
#define IDC_STATIC_CURRENT_VERSION      1039
#define IDC_STATIC_LATEST_VERSION       1040
#define IDC_STATIC_UPDATE_INFO          1041
#define IDC_BUTTON_DUILIB_LINK          1042
#define ID_UI_CONTROL_LISTBOX           32792
#define ID_UI_CONTROL_BUTTON            32793
#define ID_UI_CONTROL_CONTROL           32794
#define ID_UI_CONTROL_LABEL             32795
#define ID_UI_CONTROL_TEXT              32796
#define ID_UI_CONTROL_EDIT              32797
#define ID_UI_CONTROL_OPTION            32798
#define ID_UI_CONTROL_COMBO             32799
#define ID_UI_CONTROL_PROGRESS          32800
#define ID_UI_CONTROL_SLIDER            32801
#define ID_UI_CONTROL_ACTIVEX           32802
#define ID_UI_LAYOUT_VERTICAL           32804
#define ID_UI_LAYOUT_HORIZONTAL         32806
#define ID_UI_LAYOUT_CONTAINER          32808
#define ID_UI_LAYOUT_DIALOG             32810
#define ID_UI_LAYOUT_TILE               32812
#define ID_UI_LAYOUT_TAB                32814
#define ID_PROJECT_OPEN                 32822
#define ID_TEMPLATE_OPEN                32826
#define ID_PROJECT_CLOSE                32828
#define ID_TAMPLATE_SAVE                32836
#define ID_TEMPLATE_SAVE_AS             32837
#define ID_FILE_CLOSE_ALL               32840
#define ID_DUMMY_32842                  32842
#define ID_DUMMY_32843                  32843
#define ID_DUMMY_32844                  32844
#define ID_DUMMY_32845                  32845
#define ID_MDITABS_COPY_FULLPATH        32846
#define ID_DUMMY_32847                  32847
#define ID_MDITABS_OPEN_FULLPATH        32848
#define ID_DUMMY_                       32849
#define ID_DUMMY_32850                  32850
#define ID_MDITABS_NEW_HORZ_TAB_GROUP   32851
#define ID_DUMMY_32852                  32852
#define ID_MDITABS_NEW_VERT_TAB_GROUP   32853
#define ID_DUMMY_32854                  32854
#define ID_MDITABS_MOVE_TO_NEXT_GROUP   32855
#define ID_DUMMY_32856                  32856
#define ID_MDITABS_MOVE_TO_PREV_GROUP   32857
#define ID_32858                        32858
#define ID_                             32859
#define ID_APP_CHECK_UPDATE             32860
#define ID_32861                        32861
#define ID_32862                        32862
#define ID_32863                        32863
#define ID_EDIT_DELETE                  32864
#define ID_32868                        32868
#define ID_32869                        32869
#define ID_32870                        32870
#define ID_32871                        32871
#define ID_32872                        32872
#define ID_32873                        32873
#define ID_32874                        32874
#define ID_View_Resources               32889
#define ID_View_Controls                32890
#define ID_View_Project                 32891
#define ID_View_ToolsBox                32892
#define ID_View_Property                32893

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        348
#define _APS_NEXT_COMMAND_VALUE         32900
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           351
#endif
#endif
